### ISSUE TITLE
Other Device disappears when using dtoverlay=hifiberry-dac

### ISSUE THREAD

**Issue by raspi0** [pimoroni/pirate-audio#67]
I'm using the Pirateaudio *Audio Amp SHIM (3W Mono Amp)* as well as the *respeaker 4-mic array* from seeed on raspberry pi 4.
Now whenever i use the line "dtoverlay=hifiberry-dac" in **/boot/config.txt** (as explained in the setup) the 4mic array doesn't show up anywhere anymore.
Also when using the command "cat /proc/asound/cards" only one of the cards (amp shim or mic array) shows up, depending on the dtoverlay line.
I understand this is because the "dtoverlay=hifiberry-dac" line sets the default alsa device to the amp.
I tried changing the **/etc/asound.conf** file but without any success.

So is there a way to get the card to show up without using the "dtoverlay=hifiberry-dac" line?
What exactly does the line?

**Comment by Gadgetoid** [comment]
It's unfortunately not very straight-forward, since device-tree has a last-audio-device-wins-control-of-the-I2S-bus approach. You can't have two audio drivers running at the same time.

There may be a way to write a custom device-tree overlay to handle this, but judging by seeed's custom overlays and custom drivers it doesn't look very promising.
