### ISSUE TITLE
simple mp3 player

### ISSUE THREAD

**Issue by Crushedice** [pimoroni/pirate-audio#74]
god.  Everything , has a " web interface " .
There is NO simple mp3 player project or application out there.
And even with pirate audio.
i DONT want to rely on network! 
When i am not even at home. the player doesnt do anything! 
i just ONLY want this thing to startup and PLAY MUSIC .

**Comment by Gadgetoid** [comment]
> god

THANK YOU! You know how hard it is to get people to use the right saluation around here? These mortals don't take me seriously.

Since I am omniscent, omnipotent, omnipresent and an omnivore I actually anticipated your frustration sixteen of your mortal months ago. I manifested a very basic, hackable, Python-based, offline, mp3 player to work with our Pirate Audio boards. You can find it here: https://github.com/Gadgetoid/pirate-mp3

It's deliberaetely very basic since truly godly code would be lethal for mortal beings to behold, but as a consequence it doesn't have a "web interface."
