### ISSUE TITLE
Can not use speaker as the same time using the LCD

### ISSUE THREAD

**Issue by lls1129** [pimoroni/pirate-audio#75]
I am currently trying to use pirate-audio speaker for my raspberry pi pocket pc build. The speaker is working properly, the lcd is working as well. But they are not working together. When I play something through it, at the same time I use the example code in this repo to display an image to that square lcd, the sound will break and never come back unless I restart the OS. I am new to pi and gpio configurations, does anyone have an answer to this?

**Comment by Gadgetoid** [comment]
Sounds like it could be a power supply issue, but it's hard to tell. Does it work when powered from an official supply? Have you got anywhere with this since?

I'm super pressed for time and can only really offer software support, but you might get some build & electrical debugging help from Discord: https://discord.gg/hr93ByC
